### ISSUE TITLE
无法输出多显示器

### ISSUE THREAD

**Issue by twogoods** [xueziQQ/desktop_soyo_maxsun_h110_ql3x_ql2x_opencore_efi#1]
你好，你的这个确实直接就能用，我的主板有dp、hdmi、dvi各一个口，现在核显只能输出一个口，这个hackintool里接口那块要怎么设置啊

**Comment by xueziQQ** [comment]
hackintool的用法一句两句说不清，B站上有视频教程很简单，也可以加群请教其他人，或者干脆闲鱼付费请人调efi




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xueziQQ/desktop_soyo_maxsun_h110_ql3x_ql2x_opencore_efi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月26日(星期五) 下午3:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[xueziQQ/desktop_soyo_maxsun_h110_ql3x_ql2x_opencore_efi] 无法输出多显示器 (#1)





 
你好，你的这个确实直接就能用，我的主板有dp、hdmi、dvi各一个口，现在核显只能输出一个口，这个hackintool里接口那块要怎么设置啊
